version: "3.5"
services:
  database_master:
    image: mysql:8.0.30
    container_name: "mysql_database_master"
    restart: unless-stopped
    env_file: config/.env
    ports:
      - 3306:3306
    volumes:
      - mysqldata_master:/var/lib/mysql
      - ./config/master.cnf:/etc/my.cnf
    environment:
      - TZ:${TZ}
      - MYSQL_USER:${MYSQL_USER}
      - MYSQL_PASSWORD:${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE:${MYSQL_DATABASE}

volumes:
  mysqldata_master:
