version: "3.5"
services:
  database_slave:
    image: mysql:8.0.30
    container_name: "database_slave"
    restart: unless-stopped
    env_file: config/.env

    ports:
      - 3307:3306
      
    volumes:
      - mysqldata_slave:/var/lib/mysql
      - ./config/slave.cnf:/etc/my.cnf
      
    environment:
      - TZ:${TZ}
      - MYSQL_USER:${MYSQL_USER}
      - MYSQL_PASSWORD:${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE:${MYSQL_DATABASE}

volumes:
  mysqldata_slave:
